title: Moon
subtitle: Enjoy codeing
description: wazxser
author: null
language: zh-Hans
timezone: null
url: 'https://wazxser.github.io/'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map:
  编程语言: codeing_language
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: next
deploy:
  type: git
  repo: 'https://github.com/wazxser/wazxser.github.io.git'
  branch: master
  repository: 'https://github.com/wazxser/wazxser.github.io.git'
algolia:
  applicationID: PK6RC6KUDU
  apiKey: 31b4442fc143290f177fce7bc0a3195c
  adminApiKey: 433d4543df2cb57bc5aa9c33e5671722
  indexName: wazxser
  chunkSize: 5000
